export {
  IconHome,
  IconDumbbell,
  IconShoe,
  IconHistory,
  IconGear,
  IconSearch,
  IconUser,
  IconTrophy,
  IconFlame,
  IconCalendar,
  IconChart,
  IconBook,
  IconRuler,
  IconWatch,
  IconCheckBadge,
  IconTimer,
  IconStar,
  IconMale,
  IconFemale,
} from './GymIcons';
export type { GymIconProps } from './GymIcons';
