-- ============================================================
-- Descripciones de ejercicios (catálogo público + personales)
-- ------------------------------------------------------------
-- Rellena la columna description con la forma de ejecución para
-- los ejercicios que aún no la tienen. Idempotente: cada UPDATE
-- solo toca filas con description vacía/NULL, por lo que nunca
-- pisa una descripción ya escrita a mano.
-- ============================================================

-- ── Catálogo público ─────────────────────────────────────────
UPDATE public.exercises SET description = 'Abducción de cadera en máquina o polea: abre la pierna hacia un lado sin inclinar el tronco, enfocando el glúteo medio.' WHERE name = 'Abducción de cadera' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Con mancuernas en banco inclinado o plano: abre los brazos en arco amplio y vuelve al centro apretando el pecho.' WHERE name = 'Aperturas con mancuernas' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Aperturas de pecho en polea: brazos ligeramente flexionados, lleva las manos hacia delante juntándolas sin arquear la espalda.' WHERE name = 'Aperturas en polea' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Tumbado boca arriba con rodillas flexionadas: contrae el abdomen y eleva los hombros del suelo, espalda baja pegada.' WHERE name = 'Crunch abdominal' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Curl de bíceps con barra recta: codos pegados al cuerpo, sube la barra sin balanceo y baja controlado.' WHERE name = 'Curl bíceps barra' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Curl de bíceps con mancuernas: alterna o junta los brazos, codos fijos, supinación al subir.' WHERE name = 'Curl bíceps mancuerna' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Curl de bíceps en polea baja: barra recta o cuerda, mantén los codos fijos y aprieta el bíceps arriba.' WHERE name = 'Curl en polea baja' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Curl femoral de pie en máquina: flexiona la rodilla contra la resistencia manteniendo la cadera estable.' WHERE name = 'Curl femoral de pie' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Curl femoral tumbado en máquina: flexiona las rodillas hasta acercar los talones al glúteo, sin levantar la cadera.' WHERE name = 'Curl femoral tumbado' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Curl martillo con mancuernas: agarre neutro (palmas enfrentadas), sube sin rotar, trabaja bíceps y antebrazo.' WHERE name = 'Curl martillo' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Colgado de la barra: sube hasta que el mentón supere la barra y baja controlado. Puede hacerse con agarre prono, supino o neutro.' WHERE name = 'Dominadas' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Tumbado en banco o colgado: eleva las piernas rectas o flexionadas hasta formar 90 grados sin balanceo.' WHERE name = 'Elevación de piernas' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Elevación frontal con mancuernas o disco: sube los brazos rectos hasta la altura del hombro, sin balanceo.' WHERE name = 'Elevaciones frontales' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Elevación lateral con mancuernas: sube los brazos ligeramente flexionados hasta la altura del hombro, deltoides medio.' WHERE name = 'Elevaciones laterales' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Extensión de rodilla en máquina: endereza las piernas contra la resistencia, cuádriceps, sin levantar la cadera.' WHERE name = 'Extensiones de cuádriceps' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Face pull con cuerda en polea alta: tira hacia la cara abriendo codos, retracción escapular y rotadores externos.' WHERE name = 'Face pull' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Fondos en banco: manos apoyadas detrás, flexiona los codos bajando el cuerpo y vuelve arriba empujando con el tríceps.' WHERE name = 'Fondos en banco' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Fondos en paralelas: baja el cuerpo entre las barras flexionando los codos y empuja hasta extenderlos, pecho y tríceps.' WHERE name = 'Fondos en paralelas' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Gemelos de pie en máquina: sube sobre las puntas extendiendo el tobillo, mantén la pausa arriba y baja controlado.' WHERE name = 'Gemelos de pie' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Gemelos sentado en máquina: rodillas flexionadas, sube sobre las puntas, trabaja el sóleo y la parte baja del gemelo.' WHERE name = 'Gemelos sentado' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Hip thrust con barra en banco: apoya la espalda alta en el banco, extiende la cadera hacia arriba y aprieta el glúteo arriba.' WHERE name = 'Hip thrust' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Jalón al pecho en polea alta: agarre ancho, baja la barra hasta el pecho llevando los codos a los costados y vuelve controlado.' WHERE name = 'Jalón al pecho' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Pájaros con mancuernas: torso inclinado, abre los brazos en arco hacia los lados, deltoides posterior y espalda alta.' WHERE name = 'Pájaros' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Patada de tríceps con mancuerna: torso inclinado y codo fijo, extiende el antebrazo hacia atrás sin mover el brazo.' WHERE name = 'Patada de tríceps' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Patada trasera en polea baja: con el pie en el accesorio, extiende la pierna hacia atrás apretando el glúteo.' WHERE name = 'Patada trasera en polea' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Peso muerto: agarra la barra con la espalda neutra, empuja el suelo con las piernas y extiende cadera y rodillas a la vez.' WHERE name = 'Peso muerto' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Peso muerto rumano: bisagra de cadera con piernas semi-rígidas, baja la barra por el muslo y vuelve con el glúteo.' WHERE name = 'Peso muerto rumano' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Plancha: apoya antebrazos y puntas de los pies, mantén el cuerpo en línea recta contrayendo abdomen y glúteo.' WHERE name = 'Plancha' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Prensa de piernas: empuja la plataforma con todo el pie, extiende las piernas sin bloquear las rodillas y baja controlado.' WHERE name = 'Prensa de piernas' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Press Arnold: press de hombros con mancuernas girando desde agarre supino a prono durante el recorrido.' WHERE name = 'Press Arnold' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Press banca: tumbado en banco, baja la barra al pecho con codos a 45 grados y empuja hasta extender los brazos.' WHERE name = 'Press banca' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Press banca declinado: banco en declive, foco en la parte baja del pecho, mismo patrón que el press banca plano.' WHERE name = 'Press banca declinado' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Press banca inclinado: banco a 30-45 grados, baja la barra a la clavícula y empuja, foco en la parte alta del pecho.' WHERE name = 'Press banca inclinado' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Press con mancuernas: tumbado, baja las mancuernas a la altura del pecho y empújalas hacia arriba juntándolas ligeramente.' WHERE name = 'Press con mancuernas' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Press francés: tumbado con barra o mancuernas, codos fijos apuntando arriba, baja la carga hacia la frente flexionando codos.' WHERE name = 'Press francés' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Press militar: press vertical de pie o sentado, baja la barra a la barbilla y empuja hacia arriba sin arquear la espalda.' WHERE name = 'Press militar' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Remo con barra: torso inclinado, tira la barra al abdomen llevando los codos atrás, dorsal y espalda media.' WHERE name = 'Remo con barra' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Remo con mancuerna: torso inclinado con una mancuerna en cada mano, tira hacia el abdomen sin balanceo.' WHERE name = 'Remo con mancuerna' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Remo en polea baja: sentado con agarre cerrado, tira de la barra hacia el abdomen con el torso estable, dorsal.' WHERE name = 'Remo en polea baja' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Rueda abdominal: de rodillas, rueda hacia delante manteniendo el abdomen contraído y vuelve sin dejar caer la cadera.' WHERE name = 'Rueda abdominal' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Russian twist: sentado con el tronco ligeramente inclinado, gira el torso de lado a lado con disco o balón medicinal.' WHERE name = 'Russian twist' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Sentadilla: con la barra en la espalda o sin ella, flexiona rodillas y cadera bajando hasta al menos el paralelo y vuelve.' WHERE name = 'Sentadilla' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Sentadilla búlgara: una pierna delante y el pie trasero apoyado en banco, baja en vertical y sube con la pierna delantera.' WHERE name = 'Sentadilla búlgara' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Tríceps en polea: con barra o cuerda, codos pegados al cuerpo, extiende los antebrazos hacia abajo y aprieta al final.' WHERE name = 'Tríceps polea' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Zancadas: da un paso largo hacia delante bajando hasta que ambas rodillas formen 90 grados y alterna de pierna.' WHERE name = 'Zancadas' AND (description IS NULL OR description = '');

-- ── Ejercicios de las rutinas personales del usuario ─────────
UPDATE public.exercises SET description = 'Arrancada de potencia: carga la barra desde el suelo hasta el hombro en un movimiento explosivo y encadena un press.' WHERE name = 'Power Clean' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Snatch de potencia: lleva la barra del suelo a los brazos extendidos por encima de la cabeza en un solo movimiento explosivo.' WHERE name = 'Power Snatch' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Lanzamiento de balón medicinal: de pie o sentado, lanza el balón contra la pared o a un compañero con empuje de pecho o overhead.' WHERE name = 'Lanzamiento de balón medicinal' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Oblicuos: tumbado o de pie, flexión lateral o rotación del tronco trabajando la musculatura lateral del abdomen.' WHERE name = 'Oblicuos' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Rotación externa con goma: codo pegado al costado a 90 grados, gira el antebrazo hacia fuera contra la banda, rotadores del hombro.' WHERE name = 'Rotación externa con goma' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Plancha lateral: apoyo en un antebrazo y el borde del pie, cuerpo en línea recta de lado, abdomen y oblicuos.' WHERE name = 'Plancha lateral' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Press Pallof: de pie frente a la polea, con la cuerda al pecho, extiende los brazos hacia delante resistiendo la rotación del tronco.' WHERE name = 'Press Pallof' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Sentadilla parcial: sentadilla con recorrido más corto (hasta 60-90 grados) para cargas pesadas o recuperación.' WHERE name = 'Sentadilla Parcial' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Leñador en polea: con cuerda en polea alta o baja, lleva las manos en diagonal de un hombro a la cadera opuesta girando el tronco.' WHERE name = 'Leñador en polea' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Curl de bíceps: flexiona los codos subiendo el peso hasta el hombro, codos fijos al cuerpo, con barra o mancuernas.' WHERE name = 'Curl bíceps' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Extensión de tríceps: con polea, mancuerna o barra, extiende los codos contra la resistencia manteniendo el brazo fijo.' WHERE name = 'Extensión tríceps' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Remo unilateral: remo a un brazo apoyado en banco o de pie, dorsal y espalda media, una pierna y un brazo por serie.' WHERE name = 'Remo unilateral' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Jalón abierto: jalón en polea alta con agarre ancho abierto, baja la barra al pecho con los codos abiertos.' WHERE name = 'Jalón abierto' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Prensa: empuje de piernas contra una plataforma o en máquina, extiende sin bloquear y baja controlado.' WHERE name = 'Prensa' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Curl femoral sentado: flexión de rodilla en máquina sentado, trabaja isquiotibiales y parte baja de la cadena posterior.' WHERE name = 'Femoral sentado' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Elevación de gemelos: sube sobre las puntas de los pies con carga, mantén la pausa y baja estirando el gemelo.' WHERE name = 'Elevación gemelos' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Extensiones de cuádriceps: endereza las piernas contra la resistencia en máquina, sin levantar la cadera.' WHERE name = 'Extensiones cuádriceps' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Press banca declinado (Decline): banco en declive, bajada al pecho bajo y empuje hacia arriba, foco en pecho inferior.' WHERE name = 'Press banca Decline' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Aperturas: con mancuernas o poleas, abre los brazos en arco amplio y vuelve juntándolos, foco en pectoral.' WHERE name = 'Aperturas' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Press inclinado: press con mancuernas o barra en banco inclinado, foco en la parte alta del pecho.' WHERE name = 'Press inclinado' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Crunches: tumbado boca arriba, eleva los hombros contrayendo el abdomen, espalda baja pegada al suelo.' WHERE name = 'Crunches' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Elevaciones con disco: eleva un disco frente al pecho o hacia los lados trabajando hombro y antebrazo.' WHERE name = 'Elevaciones disco' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Tríceps con cuerda: en polea alta con cuerda, extiende los antebrazos hacia abajo y separa las puntas al final.' WHERE name = 'Tríceps cuerda' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Curl martillo con mancuernas: agarre neutro, sube sin rotar, trabaja bíceps y braquiorradial.' WHERE name = 'Martillo' AND (description IS NULL OR description = '');
UPDATE public.exercises SET description = 'Remo de pie: tira de la barra o polea hacia el abdomen de pie, torso ligeramente inclinado, espalda y dorsal.' WHERE name = 'Remo de pie' AND (description IS NULL OR description = '');
